version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: orgsledger_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: orgsledger
      POSTGRES_PASSWORD: orgsledger_dev
      POSTGRES_DB: orgsledger
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: orgsledger_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: orgsledger_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    env_file:
      - apps/api/.env
    volumes:
      - ./apps/api/src:/app/apps/api/src
      - ./packages:/app/packages

volumes:
  pgdata:
  redisdata:
