// ============================================================
// OrgsLedger API — Email Service
// ============================================================

import nodemailer from 'nodemailer';
import { config } from '../config';
import { logger } from '../logger';

let transporter: nodemailer.Transporter | null = null;

function getTransporter(): nodemailer.Transporter {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
    });
  }
  return transporter;
}

export interface EmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  text?: string;
  attachments?: Array<{
    filename: string;
    content: string | Buffer;
    contentType?: string;
  }>;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  try {
    if (!config.email.host) {
      logger.warn('SMTP not configured, email not sent', { to: options.to, subject: options.subject });
      return false;
    }

    const transport = getTransporter();
    await transport.sendMail({
      from: config.email.from,
      to: Array.isArray(options.to) ? options.to.join(', ') : options.to,
      subject: options.subject,
      html: options.html,
      text: options.text,
      attachments: options.attachments,
    });

    logger.info('Email sent', { to: options.to, subject: options.subject });
    return true;
  } catch (err) {
    logger.error('Failed to send email', err);
    return false;
  }
}

/**
 * Send meeting minutes via email to all attendees.
 */
export async function sendMeetingMinutesEmail(
  meetingTitle: string,
  minutesSummary: string,
  recipientEmails: string[]
): Promise<void> {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: #1a1a2e;">Meeting Minutes: ${meetingTitle}</h2>
      <div style="background: #f5f5f5; padding: 20px; border-radius: 8px; margin: 16px 0;">
        ${minutesSummary.replace(/\n/g, '<br/>')}
      </div>
      <p style="color: #666; font-size: 12px;">
        Generated by OrgsLedger AI — View full minutes in the app.
      </p>
    </div>
  `;

  await sendEmail({
    to: recipientEmails,
    subject: `Meeting Minutes: ${meetingTitle}`,
    html,
    text: minutesSummary,
  });
}
