// ============================================================
// OrgsLedger API — Email Service
// ============================================================

import nodemailer from 'nodemailer';
import { config } from '../config';
import { logger } from '../logger';

let transporter: nodemailer.Transporter | null = null;

function getTransporter(): nodemailer.Transporter {
  if (!transporter) {
    const isSSL = config.email.port === 465;
    transporter = nodemailer.createTransport({
      host: config.email.host,
      port: config.email.port,
      secure: isSSL,               // true for 465 (SSL), false for 587 (STARTTLS)
      auth: {
        user: config.email.user,
        pass: config.email.pass,
      },
      tls: {
        rejectUnauthorized: true,  // enforce valid certificates
      },
    });
  }
  return transporter;
}

export interface EmailOptions {
  to: string | string[];
  subject: string;
  html: string;
  text?: string;
  attachments?: Array<{
    filename: string;
    content: string | Buffer;
    contentType?: string;
  }>;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  try {
    if (!config.email.host) {
      logger.warn('SMTP not configured, email not sent', { to: options.to, subject: options.subject });
      return false;
    }

    const transport = getTransporter();
    await transport.sendMail({
      from: config.email.from,
      to: Array.isArray(options.to) ? options.to.join(', ') : options.to,
      subject: options.subject,
      html: options.html,
      text: options.text,
      attachments: options.attachments,
    });

    logger.info('Email sent', { to: options.to, subject: options.subject });
    return true;
  } catch (err) {
    logger.error('Failed to send email', err);
    return false;
  }
}

/**
 * Send meeting minutes via email to all attendees.
 */
export async function sendMeetingMinutesEmail(
  meetingTitle: string,
  minutesSummary: string,
  recipientEmails: string[]
): Promise<void> {
  const html = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <div style="background: #0B1426; padding: 24px; text-align: center; border-radius: 8px 8px 0 0;">
        <h1 style="color: #C9A84C; margin: 0; font-size: 24px;">OrgsLedger</h1>
      </div>
      <div style="background: #f8f9fa; padding: 32px; border-radius: 0 0 8px 8px;">
        <h2 style="color: #0B1426; margin-top: 0;">Meeting Minutes: ${meetingTitle}</h2>
        <div style="background: #fff; padding: 20px; border-radius: 8px; border: 1px solid #e5e7eb; margin: 16px 0;">
          ${minutesSummary.replace(/\n/g, '<br/>')}
        </div>
        <p style="color: #888; font-size: 12px;">
          Generated by OrgsLedger AI — View full minutes in the app.
        </p>
      </div>
      <p style="color: #aaa; font-size: 11px; text-align: center; margin-top: 16px;">&copy; ${new Date().getFullYear()} OrgsLedger. All rights reserved.</p>
    </div>
  `;

  await sendEmail({
    to: recipientEmails,
    subject: `Meeting Minutes: ${meetingTitle}`,
    html,
    text: minutesSummary,
  });
}
